packages:
  - apps/*
  - packages/*

enablePrePostScripts: true
autoInstallPeers: true
strictPeerDependencies: false

allowBuilds:
  '@embedded-postgres/darwin-arm64': true
  '@embedded-postgres/darwin-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/windows-x64': true
  '@playwright/browser-chromium': false
  '@scarf/scarf': false
  canvas: true
  cpu-features: false
  electron-winstaller: true
  esbuild: true
  protobufjs: false
  ssh2: false
  unix-dgram: false
