import type { MutableRefObject, RefObject } from 'react';
import type { ChartThemeColors } from '@renderer/hooks/useChartColors';
import type { CanvasManager } from '@renderer/utils/canvas/CanvasManager';
import type { FootprintBar, LiquidityHeatmapSnapshot, MarketEvent, VolumeProfile } from '@marketmind/types';
import type { StochasticResult } from '@marketmind/types';
import type { IndicatorParams } from '@renderer/store/indicatorStore';
import type { UseChartIndicatorsResult } from './useChartIndicators';

export interface UseChartIndicatorRenderersProps {
  manager: CanvasManager | null;
  colors: ChartThemeColors;
  chartType?: string;
  indicatorData: UseChartIndicatorsResult;
  indicatorParams?: IndicatorParams;
  stochasticData: StochasticResult | null;
  showEventRow: boolean;
  marketEvents: MarketEvent[];
  cvdValuesRef: RefObject<(number | null)[]>;
  imbalanceValuesRef: RefObject<(number | null)[]>;
  volumeProfile?: VolumeProfile | null;
  footprintBars?: FootprintBar[];
  heatmapDataRef: MutableRefObject<LiquidityHeatmapSnapshot | null>;
}

export interface UseChartIndicatorRenderersResult {
  renderStochastic: () => void;
  renderRSI: () => void;
  renderRSI14: () => void;
  renderBollingerBands: () => void;
  renderATR: () => void;
  renderDailyVWAP: () => void;
  renderWeeklyVWAP: () => void;
  renderVWAP: () => void;
  renderParabolicSAR: () => void;
  renderKeltner: () => void;
  renderDonchian: () => void;
  renderSupertrend: () => void;
  renderIchimoku: () => void;
  renderOBV: () => void;
  renderCMF: () => void;
  renderStochRSI: () => void;
  renderMACD: () => void;
  renderADX: () => void;
  renderWilliamsR: () => void;
  renderCCI: () => void;
  renderKlinger: () => void;
  renderElderRay: () => void;
  renderAroon: () => void;
  renderVortex: () => void;
  renderMFI: () => void;
  renderROC: () => void;
  renderAO: () => void;
  renderTSI: () => void;
  renderPPO: () => void;
  renderCMO: () => void;
  renderUltimateOsc: () => void;
  renderDEMA: () => void;
  renderTEMA: () => void;
  renderWMA: () => void;
  renderHMA: () => void;
  renderPivotPoints: () => void;
  renderFibonacci: () => void;
  renderFVG: () => void;
  renderLiquidityLevels: () => void;
  renderEventScale: () => void;
  renderCVD: () => void;
  renderImbalance: () => void;
  renderVolumeProfile: () => void;
  renderFootprint: () => void;
  renderSessionBoundaries: () => void;
  renderORB: () => void;
  renderLiquidityHeatmap: () => void;
  renderMAIndicators: () => void;
  getEventAtPosition: (x: number, y: number) => MarketEvent | null;
  renderAllOverlayIndicators: () => void;
  renderAllPanelIndicators: () => void;
}
