export const AI_TRADING_CONSTANTS = {
  MIN_KLINES_FOR_ANALYSIS: 20,
  MIN_KLINES_FOR_SETUP_DETECTION: 50,
  RECENT_KLINES_LOOKBACK: 10,

  CONFIDENCE_THRESHOLDS: {
    HIGH: 70,
    MEDIUM: 50,
    LOW: 30,
  },

  CONFIDENCE_MULTIPLIERS: {
    HIGH: 1.0,
    MEDIUM: 0.7,
    LOW: 0.5,
  },

  RISK_REWARD_THRESHOLDS: {
    CONSERVATIVE: 2.0,
    MODERATE: 1.5,
    AGGRESSIVE: 1.0,
  },

  PRICE_CHANGE_THRESHOLDS: {
    CONSERVATIVE: 2.0,
    MODERATE: 1.0,
    AGGRESSIVE: 0.5,
  },

  MIN_TRADE_AMOUNT_PERCENT: 0.01,
  QUANTITY_DECIMAL_PLACES: 5,
  QUANTITY_PRECISION_FACTOR: 100000,

  DEFAULT_ANALYSIS_INTERVAL_MS: 5 * 60 * 1000,
  HOURLY_RESET_MS: 60 * 60 * 1000,

  DEFAULT_STOP_LOSS_MULTIPLIERS: {
    LONG: 0.98,
    SHORT: 1.02,
  },

  DEFAULT_TAKE_PROFIT_MULTIPLIERS: {
    LONG: 1.06,
    SHORT: 0.94,
  },
} as const;

export const CONTEXT_AGGREGATOR_CONSTANTS = {
  DEFAULT_NEWS_LOOKBACK_HOURS: 24,
  DEFAULT_EVENTS_LOOKFORWARD_DAYS: 7,
  DEFAULT_FEAR_GREED_INDEX: 50,
  DEFAULT_BTC_DOMINANCE: 50,

  SENTIMENT_THRESHOLDS: {
    BULLISH: 60,
    BEARISH: 40,
  },

  SENTIMENT_WEIGHTS: {
    NEWS: 0.7,
    FEAR_INDEX: 0.3,
  },

  SENTIMENT_SCORE_THRESHOLDS: {
    BULLISH: 0.2,
    BEARISH: -0.2,
  },

  MAX_NEWS_ARTICLES: 10,
} as const;

export type AITradingConstants = typeof AI_TRADING_CONSTANTS;
export type ContextAggregatorConstants = typeof CONTEXT_AGGREGATOR_CONSTANTS;
