import type { MarketSession } from '@marketmind/types';

export const MARKET_SESSIONS: MarketSession[] = [
  {
    id: 'nyse',
    name: 'New York Stock Exchange',
    shortName: 'NYSE',
    country: 'US',
    timezone: 'America/New_York',
    openTime: { hour: 9, minute: 30 },
    closeTime: { hour: 16, minute: 0 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'us' },
    enabled: true,
    color: '#3B82F6',
  },
  {
    id: 'nasdaq',
    name: 'NASDAQ',
    shortName: 'NASDAQ',
    country: 'US',
    timezone: 'America/New_York',
    openTime: { hour: 9, minute: 30 },
    closeTime: { hour: 16, minute: 0 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'us' },
    enabled: false,
    color: '#6366F1',
  },
  {
    id: 'tse',
    name: 'Tokyo Stock Exchange',
    shortName: 'TSE',
    country: 'JP',
    timezone: 'Asia/Tokyo',
    openTime: { hour: 9, minute: 0 },
    closeTime: { hour: 15, minute: 0 },
    lunchBreak: {
      start: { hour: 11, minute: 30 },
      end: { hour: 12, minute: 30 },
    },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'jp' },
    enabled: true,
    color: '#EF4444',
  },
  {
    id: 'sse',
    name: 'Shanghai Stock Exchange',
    shortName: 'SSE',
    country: 'CN',
    timezone: 'Asia/Shanghai',
    openTime: { hour: 9, minute: 30 },
    closeTime: { hour: 15, minute: 0 },
    lunchBreak: {
      start: { hour: 11, minute: 30 },
      end: { hour: 13, minute: 0 },
    },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'cn' },
    enabled: true,
    color: '#F59E0B',
  },
  {
    id: 'szse',
    name: 'Shenzhen Stock Exchange',
    shortName: 'SZSE',
    country: 'CN',
    timezone: 'Asia/Shanghai',
    openTime: { hour: 9, minute: 30 },
    closeTime: { hour: 15, minute: 0 },
    lunchBreak: {
      start: { hour: 11, minute: 30 },
      end: { hour: 13, minute: 0 },
    },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'cn' },
    enabled: false,
    color: '#F97316',
  },
  {
    id: 'hkex',
    name: 'Hong Kong Stock Exchange',
    shortName: 'HKEX',
    country: 'HK',
    timezone: 'Asia/Hong_Kong',
    openTime: { hour: 9, minute: 30 },
    closeTime: { hour: 16, minute: 0 },
    lunchBreak: {
      start: { hour: 12, minute: 0 },
      end: { hour: 13, minute: 0 },
    },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'hk' },
    enabled: false,
    color: '#EC4899',
  },
  {
    id: 'lse',
    name: 'London Stock Exchange',
    shortName: 'LSE',
    country: 'GB',
    timezone: 'Europe/London',
    openTime: { hour: 8, minute: 0 },
    closeTime: { hour: 16, minute: 30 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'gb' },
    enabled: true,
    color: '#8B5CF6',
  },
  {
    id: 'euronext',
    name: 'Euronext Paris',
    shortName: 'ENX',
    country: 'FR',
    timezone: 'Europe/Paris',
    openTime: { hour: 9, minute: 0 },
    closeTime: { hour: 17, minute: 30 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'eu' },
    enabled: false,
    color: '#14B8A6',
  },
  {
    id: 'xetra',
    name: 'Deutsche Börse Xetra',
    shortName: 'XETRA',
    country: 'DE',
    timezone: 'Europe/Berlin',
    openTime: { hour: 9, minute: 0 },
    closeTime: { hour: 17, minute: 30 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'de' },
    enabled: false,
    color: '#0EA5E9',
  },
  {
    id: 'asx',
    name: 'Australian Securities Exchange',
    shortName: 'ASX',
    country: 'AU',
    timezone: 'Australia/Sydney',
    openTime: { hour: 10, minute: 0 },
    closeTime: { hour: 16, minute: 0 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'au' },
    enabled: true,
    color: '#10B981',
  },
  {
    id: 'bse',
    name: 'BSE India',
    shortName: 'BSE',
    country: 'IN',
    timezone: 'Asia/Kolkata',
    openTime: { hour: 9, minute: 15 },
    closeTime: { hour: 15, minute: 30 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'in' },
    enabled: false,
    color: '#84CC16',
  },
  {
    id: 'krx',
    name: 'Korea Exchange',
    shortName: 'KRX',
    country: 'KR',
    timezone: 'Asia/Seoul',
    openTime: { hour: 9, minute: 0 },
    closeTime: { hour: 15, minute: 30 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'kr' },
    enabled: false,
    color: '#A855F7',
  },
  {
    id: 'b3',
    name: 'B3 Brasil Bolsa Balcão',
    shortName: 'B3',
    country: 'BR',
    timezone: 'America/Sao_Paulo',
    openTime: { hour: 10, minute: 0 },
    closeTime: { hour: 17, minute: 0 },
    tradingDays: [0, 1, 2, 3, 4, 5, 6],
    icon: { type: 'flag', value: 'br' },
    enabled: false,
    color: '#22D3EE',
  },
];

// Crypto markets are 24/7 — every session above carries
// `tradingDays: [0..6]` so session-driven indicators (ORB,
// session boundaries) render every day, including weekends. The
// session's named ORB (e.g. NYSE, TSE, B3) still anchors to its
// declared open/close time in its local timezone; weekends just
// no longer get filtered out, so the user sees the same opening-
// range zones daily.

export const getEnabledSessions = (): MarketSession[] =>
  MARKET_SESSIONS.filter((session) => session.enabled);

export const getSessionById = (id: string): MarketSession | undefined =>
  MARKET_SESSIONS.find((session) => session.id === id);

export const getSessionsByCountry = (country: string): MarketSession[] =>
  MARKET_SESSIONS.filter((session) => session.country === country);
