import path from 'path';
import { defineConfig } from 'vitest/config';

const INTEGRATION_SERVICE_TESTS = [
  'src/__tests__/services/position-monitor.test.ts',
  'src/__tests__/services/position-monitor-extended.test.ts',
  'src/__tests__/services/risk-manager.test.ts',
  'src/__tests__/services/pyramiding.test.ts',
  'src/__tests__/services/pyramiding-extended.test.ts',
  'src/__tests__/services/margin-manager.test.ts',
  'src/__tests__/services/execution-manager.test.ts',
  'src/__tests__/services/opportunity-cost-manager.test.ts',
  'src/__tests__/services/cooldown.test.ts',
  'src/__tests__/services/binance-futures-user-stream.test.ts',
  'src/__tests__/services/income-events/**/*.test.ts',
];

export default defineConfig({
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      '@marketmind/types': path.resolve(__dirname, '../../packages/types/src'),

      '@marketmind/risk': path.resolve(__dirname, '../../packages/risk/src'),
    },
  },
  test: {
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: [
        'node_modules/',
        'src/__tests__/',
        '**/*.d.ts',
        '**/*.config.*',
        '**/dist/',
        'src/db/migrations/',
        'src/cli/',
        'src/routers/',
        'src/exchange/',
        'src/services/auto-trading-scheduler.ts',
        'src/services/backtesting/MultiWatcherBacktestEngine.ts',
        'src/services/backtesting/FullSystemOptimizer.ts',
        'src/services/backtesting/WalkForwardOptimizer.ts',
        'src/services/websocket.ts',
        'test-*.mjs',
        '**/index.ts',
        'src/db/client.ts',
        'src/db/schema.ts',
        'src/services/logger.ts',
        'src/services/auto-trading-log-buffer.ts',
        'src/services/binance-client.ts',
        'src/services/binance-exchange-info.ts',
        'src/services/binance-api-cache.ts',
        'src/services/binance-data.ts',
        'src/services/binance-futures-client.ts',
        'src/services/binance-kline-stream.ts',
        'src/services/binance-rate-limiter.ts',
        'src/services/market-client-factory.ts',
        'src/services/exchange-stream-factory.ts',
        'src/services/exchange-trailing-stop.ts',
        'src/services/protection-orders.ts',
        'src/services/oco-orders.ts',
        'src/services/price-cache.ts',
        'src/services/kline-prefetch.ts',
        'src/services/kline-cache.ts',
        'src/services/ib-historical.ts',
        'src/services/binance-historical.ts',
        'src/services/ib-kline-stream-service.ts',
        'src/services/income-sync-service.ts',
        'src/services/indicator-history.ts',
        'src/services/indicator-scheduler.ts',
        'src/services/symbol-mapping.ts',
        'src/services/strategy-performance.ts',
        'src/services/fear-greed-data.ts',
        'src/services/on-chain-data.ts',
        'src/services/market-cap-data.ts',
        'src/services/altcoin-season-index.ts',
        'src/services/btc-dominance-data.ts',
        'src/services/order-archiver.ts',
        'src/services/screener/presets.ts',
        'src/services/screener/screener-metadata.ts',
        'src/services/auto-trading/types.ts',
        'src/utils/trade-validation/types.ts',
        'src/utils/trade-validation/orchestrator.ts',
        'src/utils/trade-validation/filter-orchestrator.ts',
        'src/services/binance-futures-user-stream.ts',
        'src/services/binance-price-stream.ts',
        'src/utils/filters/sub-filter-types.ts',
        'src/services/min-notional-filter.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
    projects: [
      {
        extends: true,
        test: {
          name: 'unit',
          globals: true,
          environment: 'node',
          include: ['src/**/*.test.ts'],
          exclude: [
            '**/node_modules/**',
            '**/dist/**',
            'src/__tests__/routers/**',
            'src/__tests__/integration/**',
            ...INTEGRATION_SERVICE_TESTS,
          ],
          testTimeout: 30000,
          hookTimeout: 30000,
        },
      },
      {
        extends: true,
        test: {
          name: 'integration',
          globals: true,
          environment: 'node',
          setupFiles: './src/__tests__/setup.ts',
          globalSetup: './src/__tests__/globalSetup.ts',
          include: [
            'src/__tests__/routers/**/*.test.ts',
            'src/__tests__/integration/**/*.test.ts',
            ...INTEGRATION_SERVICE_TESTS,
          ],
          pool: 'forks',
          testTimeout: 30000,
          hookTimeout: 30000,
          fileParallelism: false,
        },
      },
    ],
  },
});
