import {
  KELLY_CRITERION,
  VOLATILITY_ADJUSTMENT,
  TIMING,
  LIQUIDATION_THRESHOLDS,
  AUTO_TRADING_CACHE as CORE_CACHE,
  AUTO_TRADING_ROTATION as CORE_ROTATION,
  AUTO_TRADING_BATCH as CORE_BATCH,
  AUTO_TRADING_API as CORE_API,
  AUTO_TRADING_ORDER as CORE_ORDER,
  AUTO_TRADING_RETRY as CORE_RETRY,
  PROTECTION_ORDER_RETRY as CORE_PROTECTION_RETRY,
} from '@marketmind/trading-core';

export const AUTO_TRADING_TIMING = {
  ...TIMING,
  ANTICIPATION_CHECK_INTERVAL_MS: 15_000,
  BACKFILL_RECHECK_MS: 30_000,
} as const;

export const AUTO_TRADING_CACHE = CORE_CACHE;

export const AUTO_TRADING_ROTATION = CORE_ROTATION;

export const AUTO_TRADING_BATCH = CORE_BATCH;

export const AUTO_TRADING_API = CORE_API;

export const AUTO_TRADING_KELLY = KELLY_CRITERION;

export const AUTO_TRADING_VOLATILITY = {
  HIGH_VOLATILITY_REDUCTION_FACTOR: VOLATILITY_ADJUSTMENT.HIGH_VOLATILITY_REDUCTION_FACTOR,
} as const;

export const AUTO_TRADING_LIQUIDATION = {
  WARNING_THRESHOLD: LIQUIDATION_THRESHOLDS.WARNING,
  DANGER_THRESHOLD: LIQUIDATION_THRESHOLDS.DANGER,
  CRITICAL_THRESHOLD: LIQUIDATION_THRESHOLDS.CRITICAL,
  ALERT_COOLDOWN_MS: 5 * 60_000,
  MAX_ALERTS_IN_MEMORY: 200,
} as const;

export const AUTO_TRADING_ORDER = CORE_ORDER;

export const AUTO_TRADING_RETRY = CORE_RETRY;

export const PROTECTION_ORDER_RETRY = CORE_PROTECTION_RETRY;

export const AUTO_TRADING = {
  TIMING: AUTO_TRADING_TIMING,
  CACHE: AUTO_TRADING_CACHE,
  ROTATION: AUTO_TRADING_ROTATION,
  BATCH: AUTO_TRADING_BATCH,
  API: AUTO_TRADING_API,
  KELLY: AUTO_TRADING_KELLY,
  VOLATILITY: AUTO_TRADING_VOLATILITY,
  LIQUIDATION: AUTO_TRADING_LIQUIDATION,
  ORDER: AUTO_TRADING_ORDER,
  RETRY: AUTO_TRADING_RETRY,
} as const;
