import { TIME_MS } from '@marketmind/types';

export const AUTO_TRADING_TIMING = {
  CANDLE_CLOSE_SAFETY_BUFFER_MS: 2000,
  CHECK_INTERVAL_MS: 5000,
  ANTICIPATION_CHECK_INTERVAL_MS: 15_000,
} as const;

export const AUTO_TRADING_CACHE = {
  DEFAULT_TTL_MS: 60_000,
  CONFIG_TTL_MS: 30_000,
  FUNDING_RATE_TTL_MS: 5 * TIME_MS.MINUTE,
} as const;

export const AUTO_TRADING_ROTATION = {
  MIN_ANTICIPATION_MS: 60_000,
  MAX_ANTICIPATION_MS: 600_000,
  MIN_PREPARATION_TIME_MS: 30_000,
} as const;

export const AUTO_TRADING_BATCH = {
  WATCHER_BATCH_SIZE: 6,
  KLINE_FETCH_BATCH_SIZE: 1000,
} as const;

export const AUTO_TRADING_API = {
  RATE_LIMIT_DELAY_MS: 200,
  GAP_TOLERANCE_MULTIPLIER: 1.5,
} as const;

export const AUTO_TRADING_KELLY = {
  DEFAULT_WIN_RATE: 0.50,
  DEFAULT_AVG_RR: 1.5,
  FRACTIONAL_KELLY: 0.25,
  MIN_TRADES_FOR_STATS: 20,
} as const;

export const AUTO_TRADING_VOLATILITY = {
  HIGH_VOLATILITY_REDUCTION_FACTOR: 0.7,
} as const;

export const AUTO_TRADING_LIQUIDATION = {
  WARNING_THRESHOLD: 0.50,
  DANGER_THRESHOLD: 0.25,
  CRITICAL_THRESHOLD: 0.10,
  ALERT_COOLDOWN_MS: 60_000,
  MAX_ALERTS_IN_MEMORY: 200,
} as const;

export const AUTO_TRADING_ORDER = {
  MIN_NOTIONAL_BUFFER: 1.1,
  DEFAULT_MIN_NOTIONAL: 5,
} as const;

export const AUTO_TRADING_RETRY = {
  MAX_RETRIES: 3,
  INITIAL_DELAY_MS: 1000,
  MAX_DELAY_MS: 30_000,
  BACKOFF_MULTIPLIER: 2,
  FETCH_TIMEOUT_MS: 30_000,
} as const;

export const PROTECTION_ORDER_RETRY = {
  MAX_ATTEMPTS: 3,
  INITIAL_DELAY_MS: 500,
  MAX_DELAY_MS: 2000,
  BACKOFF_MULTIPLIER: 2,
} as const;

export const AUTO_TRADING = {
  TIMING: AUTO_TRADING_TIMING,
  CACHE: AUTO_TRADING_CACHE,
  ROTATION: AUTO_TRADING_ROTATION,
  BATCH: AUTO_TRADING_BATCH,
  API: AUTO_TRADING_API,
  KELLY: AUTO_TRADING_KELLY,
  VOLATILITY: AUTO_TRADING_VOLATILITY,
  LIQUIDATION: AUTO_TRADING_LIQUIDATION,
  ORDER: AUTO_TRADING_ORDER,
  RETRY: AUTO_TRADING_RETRY,
} as const;
