import {
  TIME_MS,
  INTERVAL_MS,
  TRADING_DEFAULTS,
  TRAILING_STOP_CONFIG,
  BACKTEST_ENGINE_CONFIG,
  POSITION_SIZING_CONFIG,
  EXIT_CALCULATOR_CONFIG,
  VOLATILITY_CONFIG,
  PIVOT_DETECTION_CONFIG,
  DETECTOR_CONFIG as SHARED_DETECTOR_CONFIG,
  WEBSOCKET_CONFIG as SHARED_WEBSOCKET_CONFIG,
  QUERY_LIMITS as SHARED_QUERY_LIMITS,
  RISK_MANAGER_CONFIG,
  FLOAT_COMPARISON as SHARED_FLOAT_COMPARISON,
  CONTEXT_AGGREGATOR_CONFIG,
  KLINE_CONFIG,
  STABLECOINS as SHARED_STABLECOINS,
  TRADE_STATUS as SHARED_TRADE_STATUS,
  ACTIVE_TRADE_STATUSES as SHARED_ACTIVE_TRADE_STATUSES,
  ORDER_TYPE as SHARED_ORDER_TYPE,
  MARKET_TYPE as SHARED_MARKET_TYPE,
  ORDER_SIDE as SHARED_ORDER_SIDE,
  POSITION_SIDE as SHARED_POSITION_SIDE,
  EXIT_REASON as SHARED_EXIT_REASON,
  PROTECTION_CONFIG as SHARED_PROTECTION_CONFIG,
  RISK_ALERT_TYPES as SHARED_RISK_ALERT_TYPES,
  RISK_ALERT_LEVELS as SHARED_RISK_ALERT_LEVELS,
} from '@marketmind/types';

export { TIME_MS, INTERVAL_MS };

export const REQUIRED_KLINES = KLINE_CONFIG.REQUIRED_FOR_BACKTEST;

export const UNIT_MS: Record<string, number> = {
  m: TIME_MS.MINUTE,
  h: TIME_MS.HOUR,
  d: TIME_MS.DAY,
  w: TIME_MS.WEEK,
} as const;

export const TRADING_CONFIG = {
  MIN_RISK_REWARD_RATIO: TRADING_DEFAULTS.MIN_RISK_REWARD_RATIO,
  SESSION_DURATION_MS: TRADING_DEFAULTS.SESSION_DURATION_MS,
  DEFAULT_SLIPPAGE_PERCENT: TRADING_DEFAULTS.SLIPPAGE_PERCENT,
  DEFAULT_COMMISSION_PERCENT: TRADING_DEFAULTS.SLIPPAGE_PERCENT,
} as const;

export const WEBSOCKET_CONFIG = SHARED_WEBSOCKET_CONFIG;
export const DETECTOR_CONFIG = SHARED_DETECTOR_CONFIG;
export const STABLECOINS = SHARED_STABLECOINS;
export const FLOAT_COMPARISON = SHARED_FLOAT_COMPARISON;
export const POSITION_SIZING = POSITION_SIZING_CONFIG;
export const EXIT_CALCULATOR = EXIT_CALCULATOR_CONFIG;
export const BACKTEST_ENGINE = BACKTEST_ENGINE_CONFIG;
export const TRAILING_STOP = TRAILING_STOP_CONFIG;
export const VOLATILITY = VOLATILITY_CONFIG;
export const PIVOT_DETECTION = PIVOT_DETECTION_CONFIG;
export const CONTEXT_AGGREGATOR = CONTEXT_AGGREGATOR_CONFIG;
export const RISK_MANAGER = RISK_MANAGER_CONFIG;
export const QUERY_LIMITS = SHARED_QUERY_LIMITS;

export const BACKTEST_DEFAULTS = {
  EXPOSURE_MULTIPLIER: TRADING_DEFAULTS.EXPOSURE_MULTIPLIER,
  MIN_RISK_REWARD_RATIO: TRADING_DEFAULTS.MIN_RISK_REWARD_RATIO,
  MIN_RISK_REWARD_RATIO_LONG: 1.0,
  MIN_RISK_REWARD_RATIO_SHORT: 1.0,
} as const;

export const DEFAULT_ENABLED_SETUPS = [
  '7day-momentum-crypto',
  'momentum-breakout-2025',
  'nr7-breakout',
  'rsi2-mean-reversion',
  'donchian-breakout',
  'vwap-ema-cross',
  'triple-ema-confluence',
  'keltner-breakout-optimized',
  'golden-cross-sma',
  'rsi-sma-filter',
  'momentum-rotation',
  'chande-momentum-crypto',
] as const;

export const SESSION_DURATION_DAYS = 30;

export const TRADE_STATUS = SHARED_TRADE_STATUS;
export const ACTIVE_TRADE_STATUSES = SHARED_ACTIVE_TRADE_STATUSES;
export const ORDER_TYPE = SHARED_ORDER_TYPE;
export const MARKET_TYPE = SHARED_MARKET_TYPE;
export const ORDER_SIDE = SHARED_ORDER_SIDE;
export const POSITION_SIDE = SHARED_POSITION_SIDE;
export const EXIT_REASON = SHARED_EXIT_REASON;
export const PROTECTION_CONFIG = SHARED_PROTECTION_CONFIG;
export const RISK_ALERT_TYPES = SHARED_RISK_ALERT_TYPES;
export const RISK_ALERT_LEVELS = SHARED_RISK_ALERT_LEVELS;

export const ABSOLUTE_MINIMUM_KLINES = KLINE_CONFIG.ABSOLUTE_MINIMUM;
export const COOLDOWN_GAP_CHECK = KLINE_CONFIG.COOLDOWN_GAP_CHECK_MS;
export const COOLDOWN_CORRUPTION_CHECK = KLINE_CONFIG.COOLDOWN_CORRUPTION_CHECK_MS;
export const CORRUPTION_CHECK_KLINES = KLINE_CONFIG.CORRUPTION_CHECK_COUNT;
export const API_VALIDATION_RECENT_COUNT = KLINE_CONFIG.API_VALIDATION_RECENT_COUNT;

export { ADX_FILTER } from '../utils/filters';

export {
  AUTO_TRADING,
  AUTO_TRADING_TIMING,
  AUTO_TRADING_CACHE,
  AUTO_TRADING_ROTATION,
  AUTO_TRADING_BATCH,
  AUTO_TRADING_API,
  AUTO_TRADING_KELLY,
  AUTO_TRADING_VOLATILITY,
  AUTO_TRADING_LIQUIDATION,
  AUTO_TRADING_ORDER,
  AUTO_TRADING_RETRY,
  PROTECTION_ORDER_RETRY,
} from './auto-trading';

export type FloatComparisonConstants = typeof FLOAT_COMPARISON;
export type PositionSizingConstants = typeof POSITION_SIZING;
export type ExitCalculatorConstants = typeof EXIT_CALCULATOR;
export type BacktestEngineConstants = typeof BACKTEST_ENGINE;
export type TrailingStopConstants = typeof TRAILING_STOP;
export type BacktestDefaultsConstants = typeof BACKTEST_DEFAULTS;
export type VolatilityConstants = typeof VOLATILITY;
export type PivotDetectionConstants = typeof PIVOT_DETECTION;
export type ContextAggregatorConstants = typeof CONTEXT_AGGREGATOR;
export type RiskManagerConstants = typeof RISK_MANAGER;
export type QueryLimitsConstants = typeof QUERY_LIMITS;
export type TradeStatusConstants = typeof TRADE_STATUS;
export type TradeStatus = (typeof TRADE_STATUS)[keyof typeof TRADE_STATUS];
export type OrderType = (typeof ORDER_TYPE)[keyof typeof ORDER_TYPE];
export type MarketType = (typeof MARKET_TYPE)[keyof typeof MARKET_TYPE];
export type OrderSide = (typeof ORDER_SIDE)[keyof typeof ORDER_SIDE];
export type PositionSide = (typeof POSITION_SIDE)[keyof typeof POSITION_SIDE];
export type ExitReason = (typeof EXIT_REASON)[keyof typeof EXIT_REASON];
export type DetectorConfigConstants = typeof DETECTOR_CONFIG;
export type TradingConfigConstants = typeof TRADING_CONFIG;
export type WebsocketConfigConstants = typeof WEBSOCKET_CONFIG;
export type TimeMsConstants = typeof TIME_MS;
export type IntervalMsConstants = typeof INTERVAL_MS;
export type UnitMsConstants = typeof UNIT_MS;
