import { TIME_MS } from '@marketmind/types';

export const INDICATOR_CACHE = {
  ALTCOIN_SEASON_TTL: 15 * TIME_MS.MINUTE,
  ORDER_BOOK_TTL: 30 * TIME_MS.SECOND,
  INDICATOR_HISTORY_TTL: 5 * TIME_MS.MINUTE,
  SNAPSHOT_INTERVAL: 30 * TIME_MS.MINUTE,
} as const;

export const ALTCOIN_SEASON = {
  ALT_SEASON_THRESHOLD: 75,
  BTC_SEASON_THRESHOLD: 25,
  DEFAULT_TOP_COINS: 50,
  NEUTRAL_INDEX: 50,
  TOP_PERFORMERS_COUNT: 5,
} as const;

export const ORDER_BOOK = {
  WALL_THRESHOLD_MULTIPLIER: 3,
  DEFAULT_DEPTH_LIMIT: 20,
  IMBALANCE_NEUTRAL_THRESHOLD: 0.2,
  MAX_WALLS_RETURNED: 3,
  BATCH_DELAY_MS: 100,
  VALID_LIMITS: [5, 10, 20, 50, 100, 500, 1000, 5000] as const,
} as const;

export const ADX_TREND = {
  STRONG_TREND_THRESHOLD: 25,
  WEAK_TREND_THRESHOLD: 20,
  CHOPPY_MARKET_THRESHOLD: 20,
  MIN_KLINES_REQUIRED: 50,
} as const;

export const INDICATOR_HISTORY = {
  DEFAULT_DAYS: 31,
  MAX_RECORDS: 1000,
  RETENTION_DAYS: 90,
} as const;

export const ROTATION_FILTERS = {
  BTC_DOMINANCE_THRESHOLD: 60,
  BTC_DOMINANCE_BTC_BONUS: 1.3,
  BTC_DOMINANCE_ALT_PENALTY: 0.7,
  BTC_SEASON_BTC_BONUS: 1.5,
  BTC_SEASON_ALT_PENALTY: 0.5,
  ALT_SEASON_BTC_PENALTY: 0.7,
  CHOPPY_MARKET_PENALTY: 0.8,
  SELLING_PRESSURE_PENALTY: 0.7,
  ASK_WALL_PENALTY: 0.85,
  MIN_ORDER_BOOK_IMBALANCE: 0.7,
  ASK_WALL_RATIO_THRESHOLD: 2,
  DIRECTION_BONUS: 1.5,
  DIRECTION_PENALTY: 0.5,
  HYSTERESIS_THRESHOLD: 10,
  MIN_BTC_KLINES: 30,
  BTC_DEPRIORITIZE_RANK: 5,
} as const;

export const BTC_KLINE_QUERY = {
  SYMBOL: 'BTCUSDT',
  LIMIT: 100,
} as const;

export type IndicatorCacheConfig = typeof INDICATOR_CACHE;
export type AltcoinSeasonConfig = typeof ALTCOIN_SEASON;
export type OrderBookConfig = typeof ORDER_BOOK;
export type AdxTrendConfig = typeof ADX_TREND;
export type IndicatorHistoryConfig = typeof INDICATOR_HISTORY;
export type RotationFiltersConfig = typeof ROTATION_FILTERS;
