import { SCALPING_DEFAULTS } from '@marketmind/types';

export { SCALPING_DEFAULTS };

export const SCALPING_STREAM = {
  RECONNECT_DELAY_MS: 5_000,
  MAX_RECONNECT_ATTEMPTS: 10,
  SUBSCRIPTION_CHECK_INTERVAL_MS: 30_000,
  PRICE_THROTTLE_MS: 50,
} as const;

export const SCALPING_ENGINE = {
  SIGNAL_COOLDOWN_MS: 8_000,
  CVD_HISTORY_BARS: 300,
  METRICS_HISTORY_SIZE: 1_500,
  DEFAULT_TICK_SIZE: 0.01,
  VOLUME_PROFILE_MAX_LEVELS: 500,
  EXHAUSTION_LOOKBACK: 20,
  EXHAUSTION_THRESHOLD: 0.3,
  MICRO_TRAILING_MIN_INTERVAL_MS: 1_000,
  TRADE_BUFFER_RETENTION_MS: 5 * 60 * 1_000,
  VALUE_AREA_COVERAGE: 0.7,
  AVG_OVERFLOW_THRESHOLD: 2_000,
  AVG_REBALANCE_COUNT: 1_000,
  EXHAUSTION_MIN_DELTA: 0.001,
  SIGNAL_EVAL_THROTTLE_MS: 200,
  BALANCE_CACHE_TTL_MS: 10_000,
  MAX_CONSECUTIVE_LOSSES: SCALPING_DEFAULTS.MAX_CONSECUTIVE_LOSSES,
  CONSECUTIVE_LOSS_COOLDOWN_MS: SCALPING_DEFAULTS.CONSECUTIVE_LOSS_COOLDOWN_MS,
} as const;

export const SCALPING_STRATEGY = {
  IMBALANCE_SL_PERCENT: 0.002,
  IMBALANCE_TP_PERCENT: 0.003,
  CVD_DIVERGENCE_SL_PERCENT: 0.003,
  CVD_DIVERGENCE_TP_PERCENT: 0.005,
  MEAN_REVERSION_SL_PERCENT: 0.003,
  MEAN_REVERSION_TP_RATIO: 0.7,
  MOMENTUM_BURST_SL_PERCENT: 0.002,
  MOMENTUM_BURST_TP_PERCENT: 0.005,
  MOMENTUM_BURST_MIN_IMBALANCE: 0.4,
  ABSORPTION_SL_PERCENT: 0.002,
  ABSORPTION_TP_PERCENT: 0.004,
  IMBALANCE_MAX_CONFIDENCE: 95,
  IMBALANCE_BASE_CONFIDENCE: 50,
  CVD_DIVERGENCE_CONFIDENCE: 60,
  MEAN_REVERSION_MAX_CONFIDENCE: 85,
  MEAN_REVERSION_BASE_CONFIDENCE: 55,
  MOMENTUM_BURST_CONFIDENCE: 65,
  ABSORPTION_CONFIDENCE: 70,
} as const;

export const SCALPING_EXECUTION = {
  ORDER_TIMEOUT_MS: 5_000,
  CANCEL_RETRY_ATTEMPTS: 3,
  CANCEL_RETRY_DELAY_MS: 200,
  POSITION_VERIFY_DELAY_MS: 500,
} as const;

export type ScalpingStreamConstants = typeof SCALPING_STREAM;
export type ScalpingEngineConstants = typeof SCALPING_ENGINE;
export type ScalpingStrategyConstants = typeof SCALPING_STRATEGY;
export type ScalpingExecutionConstants = typeof SCALPING_EXECUTION;
