export const CHART_CONFIG = {
  DEFAULT_CANDLE_WIDTH: 8,
  MIN_CANDLE_WIDTH: 2,
  MAX_CANDLE_WIDTH: 50,
  CANDLE_SPACING: 2,
  CANVAS_PADDING: 40,
  CANVAS_PADDING_LEFT: 10,
  CANVAS_PADDING_RIGHT: 64,
  CANVAS_PADDING_TOP: 10,
  CANVAS_PADDING_BOTTOM: 25,
  CHART_RIGHT_MARGIN: 72,
  VOLUME_HEIGHT_RATIO: 0.25,
  GRID_LINE_WIDTH: 1,
  CANDLE_WICK_WIDTH: 1,
  CURRENT_PRICE_LINE_WIDTH: 2,
  CURRENT_PRICE_LINE_STYLE: 'dashed' as const,
  AXIS_LABEL_FONT: '11px monospace',
} as const;

export const DEFAULT_MA_PERIODS = [20, 50, 200] as const;
