ALTER TABLE "trading_profiles" ADD COLUMN "trading_mode" varchar(20);
ALTER TABLE "trading_profiles" ADD COLUMN "direction_mode" varchar(15);
ALTER TABLE "trading_profiles" ADD COLUMN "position_size_percent" numeric(5, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "use_trend_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_adx_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_choppiness_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_vwap_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_stochastic_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_stochastic_recovery_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_momentum_timing_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_btc_correlation_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_volume_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_direction_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_super_trend_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_market_regime_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_bollinger_squeeze_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_mtf_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_stochastic_htf_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_stochastic_recovery_htf_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_funding_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_fvg_filter" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_confluence_scoring" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "confluence_min_score" integer;
ALTER TABLE "trading_profiles" ADD COLUMN "use_cooldown" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "cooldown_minutes" integer;
ALTER TABLE "trading_profiles" ADD COLUMN "fibonacci_target_level_long" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "fibonacci_target_level_short" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "fibonacci_swing_range" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "max_fibonacci_entry_progress_percent_long" numeric(5, 1);
ALTER TABLE "trading_profiles" ADD COLUMN "max_fibonacci_entry_progress_percent_short" numeric(5, 1);
ALTER TABLE "trading_profiles" ADD COLUMN "initial_stop_mode" varchar(20);
ALTER TABLE "trading_profiles" ADD COLUMN "tp_calculation_mode" varchar(20);
ALTER TABLE "trading_profiles" ADD COLUMN "min_risk_reward_ratio_long" numeric(4, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "min_risk_reward_ratio_short" numeric(4, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_stop_enabled" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_stop_mode" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_activation_percent_long" numeric(5, 4);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_activation_percent_short" numeric(5, 4);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_distance_percent_long" numeric(5, 4);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_distance_percent_short" numeric(5, 4);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_distance_mode" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_stop_offset_percent" numeric(5, 4);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_activation_mode_long" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "trailing_activation_mode_short" varchar(10);
ALTER TABLE "trading_profiles" ADD COLUMN "use_adaptive_trailing" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "max_drawdown_enabled" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "max_drawdown_percent" numeric(5, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "daily_loss_limit" numeric(10, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "max_risk_per_stop_enabled" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "max_risk_per_stop_percent" numeric(5, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "choppiness_threshold_high" numeric(5, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "choppiness_threshold_low" numeric(5, 2);
ALTER TABLE "trading_profiles" ADD COLUMN "volume_filter_obv_lookback_long" integer;
ALTER TABLE "trading_profiles" ADD COLUMN "volume_filter_obv_lookback_short" integer;
ALTER TABLE "trading_profiles" ADD COLUMN "use_obv_check_long" boolean;
ALTER TABLE "trading_profiles" ADD COLUMN "use_obv_check_short" boolean;
