export const PATTERN_DETECTION_CONFIG = {
  PIVOT_LOOKBACK_DEFAULT: 5,
  PIVOT_LOOKAHEAD_DEFAULT: 5,
  PIVOT_LOOKBACK_MIN: 3,
  PIVOT_LOOKBACK_MAX: 10,
  
  PRICE_TOLERANCE_PERCENT: 1.5,
  TIME_TOLERANCE_CANDLES: 5,
  
  MIN_TOUCHES_SUPPORT: 2,
  MIN_TOUCHES_RESISTANCE: 2,
  STRONG_LEVEL_TOUCHES: 5,
  
  MIN_PIVOTS_TRENDLINE: 2,
  PREFERRED_PIVOTS_TRENDLINE: 3,
  MAX_TRENDLINE_DEVIATION: 0.04,
  
  MIN_CHANNEL_TOUCHES: 4,
  PARALLEL_TOLERANCE: 0.2,
  
  SHOULDER_HEIGHT_TOLERANCE: 0.08,
  DOUBLE_TOP_TOLERANCE: 0.05,
  TRIPLE_TOP_TOLERANCE: 0.08,
  
  VOLUME_SPIKE_THRESHOLD: 1.5,
  VOLUME_PERIOD: 20,
  
  MIN_CONFIDENCE_THRESHOLD: 0.3,
  HIGH_CONFIDENCE_THRESHOLD: 0.65,
  
  MIN_PATTERN_FORMATION_CANDLES: 10,
  IDEAL_PATTERN_FORMATION_CANDLES: 50,
  MIN_PATTERN_PRICE_RANGE_PERCENT: 3,
  
  GAP_MIN_PERCENT: 0.5,
  
  FIBONACCI_LEVELS: [0.236, 0.382, 0.5, 0.618, 0.786],
  FIBONACCI_EXTENSION_LEVELS: [1.272, 1.618, 2.0, 2.618],
  FIBONACCI_TOLERANCE: 0.01,
  
  MAX_PATTERNS_PER_TYPE: 5,
  DETECTION_DEBOUNCE_MS: 500,
} as const;
