/* eslint-disable @typescript-eslint/no-base-to-string -- transform fields are documented numeric/string column values; String(v) is intentional for nullable numeric DB columns */
import { stringifyDynamicSymbolExcluded, stringifyEnabledSetupTypes } from './profile-transformers';

interface ConfigFieldDef {
  key: string;
  transform?: (value: unknown) => unknown;
}

const CONFIG_FIELDS: ConfigFieldDef[] = [
  { key: 'isEnabled' },
  { key: 'maxConcurrentPositions' },
  { key: 'maxPositionSize' },
  { key: 'dailyLossLimit' },
  { key: 'enabledSetupTypes', transform: (v) => stringifyEnabledSetupTypes(v as string[]) },
  { key: 'positionSizing' },
  { key: 'useLimitOrders' },
  { key: 'volumeFilterObvLookbackLong' },
  { key: 'volumeFilterObvLookbackShort' },
  { key: 'useObvCheckLong' },
  { key: 'useObvCheckShort' },
  { key: 'positionSizePercent' },
  { key: 'manualPositionSizePercent' },
  { key: 'maxGlobalExposurePercent' },
  { key: 'tpCalculationMode' },
  { key: 'fibonacciTargetLevel' },
  { key: 'fibonacciTargetLevelLong' },
  { key: 'fibonacciTargetLevelShort' },
  { key: 'fibonacciSwingRange' },
  { key: 'initialStopMode' },
  { key: 'useDynamicSymbolSelection' },
  { key: 'dynamicSymbolRotationInterval' },
  { key: 'dynamicSymbolExcluded', transform: (v) => stringifyDynamicSymbolExcluded(v as string[]) },
  { key: 'enableAutoRotation' },
  { key: 'trailingStopMode' },
  { key: 'trailingStopEnabled' },
  { key: 'trailingActivationPercentLong' },
  { key: 'trailingActivationPercentShort' },
  { key: 'trailingDistancePercentLong' },
  { key: 'trailingDistancePercentShort' },
  { key: 'useAdaptiveTrailing' },
  { key: 'trailingDistanceMode' },
  { key: 'trailingStopOffsetPercent' },
  { key: 'trailingActivationModeLong' },
  { key: 'trailingActivationModeShort' },
  { key: 'leverage' },
  { key: 'marginType' },
  { key: 'opportunityCostEnabled' },
  { key: 'maxHoldingPeriodBars' },
  { key: 'stalePriceThresholdPercent' },
  { key: 'staleTradeAction' },
  { key: 'timeBasedStopTighteningEnabled' },
  { key: 'timeTightenAfterBars' },
  { key: 'timeTightenPercentPerBar' },
  { key: 'pyramidingEnabled' },
  { key: 'pyramidingMode' },
  { key: 'maxPyramidEntries' },
  { key: 'pyramidProfitThreshold' },
  { key: 'pyramidScaleFactor' },
  { key: 'pyramidMinDistance' },
  { key: 'pyramidUseAtr' },
  { key: 'pyramidUseAdx' },
  { key: 'pyramidUseRsi' },
  { key: 'pyramidAdxThreshold' },
  { key: 'pyramidRsiLowerBound' },
  { key: 'pyramidRsiUpperBound' },
  { key: 'pyramidFiboLevels', transform: (v) => JSON.stringify(v) },
  { key: 'leverageAwarePyramid' },
  { key: 'directionMode' },
  { key: 'minRiskRewardRatioLong' },
  { key: 'minRiskRewardRatioShort' },
  { key: 'maxFibonacciEntryProgressPercentLong', transform: (v) => String(v) },
  { key: 'maxFibonacciEntryProgressPercentShort', transform: (v) => String(v) },
  { key: 'maxDrawdownEnabled' },
  { key: 'maxDrawdownPercent' },
  { key: 'maxRiskPerStopEnabled' },
  { key: 'maxRiskPerStopPercent' },
  { key: 'marginTopUpEnabled' },
  { key: 'marginTopUpThreshold' },
  { key: 'marginTopUpPercent' },
  { key: 'marginTopUpMaxCount' },
  { key: 'positionMode' },
  { key: 'tradingMode' },
  { key: 'sessionScanEnabled' },
  { key: 'sessionScanMarkets' },
  { key: 'useProfitLockDistance' },
  { key: 'useCooldown' },
  { key: 'cooldownMinutes' },
  { key: 'choppinessThresholdHigh' },
  { key: 'choppinessThresholdLow' },
  { key: 'choppinessPeriod' },
  { key: 'useSessionFilter' },
  { key: 'sessionStartUtc' },
  { key: 'sessionEndUtc' },
  { key: 'useBollingerSqueezeFilter' },
  { key: 'bollingerSqueezeThreshold' },
  { key: 'bollingerSqueezePeriod' },
  { key: 'bollingerSqueezeStdDev' },
  { key: 'useVwapFilter' },
  { key: 'useSuperTrendFilter' },
  { key: 'superTrendPeriod' },
  { key: 'superTrendMultiplier' },
  { key: 'useChoppinessFilter' },
  { key: 'useConfluenceScoring' },
  { key: 'confluenceMinScore' },
  { key: 'useFvgFilter' },
  { key: 'autoCancelOrphans' },
];

const applyFieldsToUpdate = (
  fields: ConfigFieldDef[],
  input: Record<string, unknown>,
  updateData: Record<string, unknown>,
): void => {
  for (const field of fields) {
    if (input[field.key] !== undefined) {
      updateData[field.key] = field.transform
        ? field.transform(input[field.key])
        : input[field.key];
    }
  }
};

export const applyConfigFieldsToUpdate = (
  input: Record<string, unknown>,
  updateData: Record<string, unknown>,
): void => applyFieldsToUpdate(CONFIG_FIELDS, input, updateData);

const TRADING_PROFILE_FIELDS: ConfigFieldDef[] = [
  { key: 'name' },
  { key: 'description' },
  { key: 'enabledSetupTypes', transform: (v) => stringifyEnabledSetupTypes(v as string[]) },
  { key: 'maxPositionSize', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'maxConcurrentPositions' },
  { key: 'isDefault' },
  { key: 'tradingMode' },
  { key: 'directionMode' },
  { key: 'positionSizePercent', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'useTrendFilter' },
  { key: 'useAdxFilter' },
  { key: 'useChoppinessFilter' },
  { key: 'useVwapFilter' },
  { key: 'useStochasticFilter' },
  { key: 'useStochasticRecoveryFilter' },
  { key: 'useMomentumTimingFilter' },
  { key: 'useBtcCorrelationFilter' },
  { key: 'useVolumeFilter' },
  { key: 'useDirectionFilter' },
  { key: 'useSuperTrendFilter' },
  { key: 'useMarketRegimeFilter' },
  { key: 'useBollingerSqueezeFilter' },
  { key: 'useMtfFilter' },
  { key: 'useStochasticHtfFilter' },
  { key: 'useStochasticRecoveryHtfFilter' },
  { key: 'useFundingFilter' },
  { key: 'useFvgFilter' },
  { key: 'useConfluenceScoring' },
  { key: 'confluenceMinScore' },
  { key: 'useCooldown' },
  { key: 'cooldownMinutes' },
  { key: 'fibonacciTargetLevelLong' },
  { key: 'fibonacciTargetLevelShort' },
  { key: 'fibonacciSwingRange' },
  { key: 'maxFibonacciEntryProgressPercentLong', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'maxFibonacciEntryProgressPercentShort', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'initialStopMode' },
  { key: 'tpCalculationMode' },
  { key: 'minRiskRewardRatioLong', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'minRiskRewardRatioShort', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingStopEnabled' },
  { key: 'trailingStopMode' },
  { key: 'trailingActivationPercentLong', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingActivationPercentShort', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingDistancePercentLong', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingDistancePercentShort', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingDistanceMode' },
  { key: 'trailingStopOffsetPercent', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'trailingActivationModeLong' },
  { key: 'trailingActivationModeShort' },
  { key: 'useAdaptiveTrailing' },
  { key: 'maxDrawdownEnabled' },
  { key: 'maxDrawdownPercent', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'dailyLossLimit', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'maxRiskPerStopEnabled' },
  { key: 'maxRiskPerStopPercent', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'choppinessThresholdHigh', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'choppinessThresholdLow', transform: (v) => v !== null && v !== undefined ? String(v) : null },
  { key: 'volumeFilterObvLookbackLong' },
  { key: 'volumeFilterObvLookbackShort' },
  { key: 'useObvCheckLong' },
  { key: 'useObvCheckShort' },
];

export const applyProfileFieldsToUpdate = (
  input: Record<string, unknown>,
  updateData: Record<string, unknown>,
): void => applyFieldsToUpdate(TRADING_PROFILE_FIELDS, input, updateData);
