import { TIME_MS } from '@marketmind/types';

export const KELLY_CRITERION = {
  DEFAULT_WIN_RATE: 0.50,
  DEFAULT_AVG_RR: 1.5,
  FRACTIONAL_KELLY: 0.25,
  MIN_TRADES_FOR_STATS: 20,
  MAX_KELLY_FRACTION: 0.10,
} as const;

export const VOLATILITY_ADJUSTMENT = {
  HIGH_VOLATILITY_REDUCTION_FACTOR: 0.7,
  ATR_HIGH_THRESHOLD: 3.0,
} as const;

export const TIMING = {
  CANDLE_CLOSE_SAFETY_BUFFER_MS: 2000,
  CHECK_INTERVAL_MS: 15_000,
  TRAILING_STOP_INTERVAL_MS: 60_000,
  OPPORTUNITY_COST_INTERVAL_MS: 60_000,
  MARGIN_CHECK_INTERVAL_MS: 60_000,
  POSITION_CHECK_THROTTLE_MS: 500,
  SUBSCRIPTION_CHECK_INTERVAL_MS: 300_000,
} as const;

export const LIQUIDATION_THRESHOLDS = {
  WARNING: 0.15,
  DANGER: 0.08,
  CRITICAL: 0.05,
} as const;

export const AUTO_TRADING_CACHE = {
  DEFAULT_TTL_MS: 60_000,
  CONFIG_TTL_MS: 30_000,
  FUNDING_RATE_TTL_MS: 5 * TIME_MS.MINUTE,
} as const;

export const AUTO_TRADING_ROTATION = {
  MIN_ANTICIPATION_MS: 60_000,
  MAX_ANTICIPATION_MS: 600_000,
  MIN_PREPARATION_TIME_MS: 30_000,
} as const;

export const AUTO_TRADING_BATCH = {
  WATCHER_BATCH_SIZE: 6,
  KLINE_FETCH_BATCH_SIZE: 1000,
} as const;

export const AUTO_TRADING_API = {
  RATE_LIMIT_DELAY_MS: 200,
  GAP_TOLERANCE_MULTIPLIER: 1.5,
} as const;

export const AUTO_TRADING_ORDER = {
  MIN_NOTIONAL_BUFFER: 1.1,
  DEFAULT_MIN_NOTIONAL: 5,
} as const;

export const AUTO_TRADING_RETRY = {
  MAX_RETRIES: 3,
  INITIAL_DELAY_MS: 1000,
  MAX_DELAY_MS: 30_000,
  BACKOFF_MULTIPLIER: 2,
  FETCH_TIMEOUT_MS: 30_000,
} as const;

export const PROTECTION_ORDER_RETRY = {
  MAX_ATTEMPTS: 3,
  INITIAL_DELAY_MS: 500,
  MAX_DELAY_MS: 2000,
  BACKOFF_MULTIPLIER: 2,
} as const;

export const TRADING_CORE_CONSTANTS = {
  KELLY: KELLY_CRITERION,
  VOLATILITY: VOLATILITY_ADJUSTMENT,
  TIMING,
  LIQUIDATION: LIQUIDATION_THRESHOLDS,
  CACHE: AUTO_TRADING_CACHE,
  ROTATION: AUTO_TRADING_ROTATION,
  BATCH: AUTO_TRADING_BATCH,
  API: AUTO_TRADING_API,
  ORDER: AUTO_TRADING_ORDER,
  RETRY: AUTO_TRADING_RETRY,
} as const;
